<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LegacyBanking.Domain\LegacyBanking.Domain.csproj" />
    <ProjectReference Include="..\LegacyBanking.Data\LegacyBanking.Data.csproj" />
    <ProjectReference Include="..\LegacyBanking.Integrations\LegacyBanking.Integrations.csproj" />
  </ItemGroup>
</Project>
