CREATE DATABASE SecureCommerce;
GO
USE SecureCommerce;
GO

CREATE TABLE Users(Id INT IDENTITY PRIMARY KEY, Email NVARCHAR(256) NOT NULL,
PasswordHash NVARCHAR(500) NOT NULL, Role NVARCHAR(50) NOT NULL,
DisplayName NVARCHAR(200), IsActive BIT NOT NULL);

CREATE TABLE Products(Id INT IDENTITY PRIMARY KEY, Sku NVARCHAR(100) NOT NULL,
Name NVARCHAR(300) NOT NULL, Price DECIMAL(18,2) NOT NULL,
Stock INT NOT NULL, IsActive BIT NOT NULL);

CREATE TABLE Orders(Id INT IDENTITY PRIMARY KEY, UserId INT NOT NULL,
GrossAmount DECIMAL(18,2) NOT NULL, DiscountAmount DECIMAL(18,2) NOT NULL,
NetAmount DECIMAL(18,2) NOT NULL, Status NVARCHAR(50) NOT NULL,
PaymentReference NVARCHAR(200), CreatedOn DATETIME2 NOT NULL);

CREATE TABLE OrderItems(Id INT IDENTITY PRIMARY KEY, OrderId INT NOT NULL,
ProductId INT NOT NULL, Quantity INT NOT NULL,
UnitPrice DECIMAL(18,2) NOT NULL, LineTotal DECIMAL(18,2) NOT NULL);
